[package]
name = "lora-phy"
version = "2.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/embassy-rs/lora-phy"
categories = ["embedded", "no-std", "asynchronous"]
keywords = ["lora", "radio", "embedded-hal-async", "iot", "semtech"]
description = "A LoRa physical layer implementation enabling utilization of a range of MCU/LoRa board combinations within embedded frameworks supporting embedded-hal-async."

[dependencies]
defmt = { version = "0.3" }
log = { version = "0.4.14" }
lorawan-device = { version = "0.10", default-features = false, features = ["async"], optional = true }
num-traits = { version = "0.2.14", default-features = false }

embedded-hal-async = { version = "=0.2.0-alpha.2"}

[features]
lorawan-device = ["dep:lorawan-device"]
